param(
  [string]$MemoryRoot = '.runtime/active_compact_semantic_memory_v1',
  [string]$VectorMapPath = 'operations/school/curriculum/development_vector/school_development_vector_map_v1.json',
  [string]$RequestedTopics = 'AUTO',
  [ValidateRange(1,1000)][int]$PatchSize = 1000,
  [string]$OutputPath = '.runtime/school_dynamic_theme_selection/latest_selection.json',
  [ValidateRange(1,50)][int]$Top = 12
)
$ErrorActionPreference='Stop'
$repoRoot=(git rev-parse --show-toplevel).Trim(); Set-Location $repoRoot
function WriteJson($Path,$Obj,$Depth=60){ $dir=Split-Path -Parent $Path; if($dir){New-Item -ItemType Directory -Force -Path $dir|Out-Null}; $Obj|ConvertTo-Json -Depth $Depth|Set-Content -LiteralPath $Path -Encoding UTF8 }
function NormalizeTopic($s){ $x=([string]$s).Trim().ToLowerInvariant(); $x=[regex]::Replace($x,'[^\p{L}\p{Nd}]+','_').Trim('_'); if([string]::IsNullOrWhiteSpace($x)){$x='unknown_topic'}; $x }
function EstimateDepth($c){ if($null -eq $c){return 0}; $obs=0; [void][int]::TryParse([string]$c.observation_count,[ref]$obs); $txt=(@($c.label,$c.concept_key,$c.summary,$c.definition,$c.expected_behavior,$c.return_to_parent,$c.properties,$c.relations,$c.uses)-join ' '); $d=1; if($obs -ge 10 -or ([Text.Encoding]::UTF8.GetByteCount([string]$c.summary)) -ge 250){$d=2}; if($txt -match '(?i)proof|evidence' -and $txt -match '(?i)validator|validation'){$d=3}; if($txt -match '(?i)return_to_parent|return' -and $txt -match '(?i)source' -and $obs -ge 50){$d=4}; if($obs -ge 100 -and $txt -match '(?i)proof|evidence' -and $txt -match '(?i)validator|validation' -and $txt -match '(?i)return_to_parent|return'){$d=5}; return $d }
if(-not(Test-Path $VectorMapPath)){throw "VECTOR_MAP_MISSING:$VectorMapPath"}
$vector=Get-Content $VectorMapPath -Raw|ConvertFrom-Json
if($vector.status -ne 'ACTIVE'){throw "VECTOR_MAP_NOT_ACTIVE:$($vector.status)"}
$topics=@($vector.topics); if($topics.Count -lt 1){throw 'VECTOR_TOPICS_EMPTY'}
$requested=@(); $requestedMode=$RequestedTopics.Trim().ToUpperInvariant(); if(-not [string]::IsNullOrWhiteSpace($RequestedTopics) -and $requestedMode -notin @('AUTO','DEFAULT')){$requested=@($RequestedTopics -split ','|ForEach-Object{NormalizeTopic $_}|Select-Object -Unique)}
$vectorRanked=@($topics|Sort-Object @{Expression={[int]$_.priority_queue};Ascending=$true},topic_key)
$selectedBase=$null; $selectionReason='independent_vector_priority'
if($requested.Count -gt 0){ $req=$requested[0]; $selectedBase=$topics|Where-Object{(NormalizeTopic $_.topic_key)-eq $req -or (NormalizeTopic $_.label)-eq $req}|Select-Object -First 1; if(-not $selectedBase){$selectedBase=[pscustomobject]@{topic_key=$req;label=$req;priority_queue=1;target_depth=3;why='Owner-requested topic';source_basis=@('Owner Topics field');codex_depth_focus='build selected Owner topic with proof and return-to-parent'} }; $selectionReason='owner_requested_topic' }
else { $selectedBase=$vectorRanked|Select-Object -First 1 }
if(-not $selectedBase){throw 'NO_TOPIC_SELECTED_BEFORE_MEMORY'}
# Owner correction boundary: topic/path is now fixed. Only after this point may relevant memory be read.
if(-not(Test-Path $MemoryRoot)){throw "MEMORY_ROOT_NOT_FOUND:$MemoryRoot"}
$manifestPath=Join-Path $MemoryRoot 'manifest.json'; $cellsPath=Join-Path $MemoryRoot 'cells.jsonl'
if(-not(Test-Path $manifestPath)){throw 'MEMORY_MANIFEST_MISSING'}; if(-not(Test-Path $cellsPath)){throw 'MEMORY_CELLS_MISSING'}
$manifest=Get-Content $manifestPath -Raw|ConvertFrom-Json; if($manifest.status -notlike 'PASS_*'){throw "MEMORY_NOT_PASS:$($manifest.status)"}
$selectedKey=NormalizeTopic $selectedBase.topic_key; $selectedLabel=NormalizeTopic $selectedBase.label
$matched=$null; foreach($line in Get-Content $cellsPath){ if([string]::IsNullOrWhiteSpace($line)){continue}; $c=$line|ConvertFrom-Json; $keys=@((NormalizeTopic $c.theme_key),(NormalizeTopic $c.concept_key),(NormalizeTopic $c.label)); if($keys -contains $selectedKey -or $keys -contains $selectedLabel){$matched=$c; break} }
$currentDepth=EstimateDepth $matched; $targetDepth=[int]$selectedBase.target_depth; $gap=[Math]::Max(0,$targetDepth-$currentDepth)
$selected=[pscustomobject]@{ selection_reason=$selectionReason; topic_key=[string]$selectedBase.topic_key; label=[string]$selectedBase.label; priority_queue=[int]$selectedBase.priority_queue; current_depth=$currentDepth; target_depth=$targetDepth; start_depth=$currentDepth; depth_gap=$gap; matched_memory_topic=if($matched){[string]$matched.concept_key}else{$null}; why=[string]$selectedBase.why; source_basis=@($selectedBase.source_basis); codex_depth_focus=[string]$selectedBase.codex_depth_focus }
$ranked=@($vectorRanked|Select-Object -First $Top|ForEach-Object{[pscustomobject]@{topic_key=[string]$_.topic_key;label=[string]$_.label;priority_queue=[int]$_.priority_queue;selection_basis='vector_only_no_memory'}})
$codexTemplate=[ordered]@{role='bounded_school_material_author';target_topic=$selected.topic_key;target_label=$selected.label;priority_queue=$selected.priority_queue;current_depth=$selected.current_depth;target_depth=$selected.target_depth;start_depth=$selected.start_depth;depth_gap=$selected.depth_gap;candidate_limit_hint=$PatchSize;single_topic_boundary="Only this topic is allowed: $($selected.topic_key). Do not broaden into adjacent topics.";depth_task="Start at depth $($selected.start_depth) and create material that advances toward depth $($selected.target_depth).";candidate_rules=@($vector.codex_task_template_contract.candidate_rules);required_fields=@($vector.codex_task_template_contract.must_include);cut_lines=@($vector.codex_task_template_contract.cut_lines);acceptance_contract=@('candidate declares topic_key exactly','candidate uses codex_school_knowledge_candidate_v1','candidate claim is declarative topic knowledge, not source-document metadata or an action request','candidate includes concrete resolvable source_basis and source_missing=false','candidate includes knowledge_kind and evidence_statement','insufficient distinct evidence fails instead of paraphrase padding','candidate includes validator and negative case','candidate includes return_to_parent relation','no active memory mutation by Codex');output_status='CODEX_DRAFT_UNTIL_SCHOOL_VALIDATED'}
$result=[ordered]@{schema='development_vector_theme_selection_v2';status='PASS_DEVELOPMENT_VECTOR_THEME_SELECTION_V2';created_at=(Get-Date).ToString('o');selection_boundary='TOPIC_SELECTED_BEFORE_MEMORY_RETRIEVAL';memory_used_for_topic_selection=$false;memory_used_after_selection_for_relevant_context=$true;memory_root=$MemoryRoot;vector_map_path=$VectorMapPath;manifest_status=$manifest.status;requested_topics_raw=$RequestedTopics;requested_topics=@($requested);patch_size=$PatchSize;expected_topic_count=$topics.Count;selected_topic=$selected;ranked_topics=@($ranked);fallback_used=$false;codex_request_template=$codexTemplate;memory_mutated=$false}
WriteJson $OutputPath $result 100
Write-Host "DYNAMIC_THEME_SELECTION_STATUS=$($result.status)"; Write-Host "DYNAMIC_THEME_SELECTED_TOPIC=$($selected.topic_key)"; Write-Host "DYNAMIC_THEME_SELECTION_REASON=$($selected.selection_reason)"; Write-Host "DYNAMIC_THEME_MEMORY_USED_FOR_SELECTION=$($result.memory_used_for_topic_selection)"; Write-Host "DYNAMIC_THEME_SELECTION_PROOF=$OutputPath"