param([string]$MemoryRoot='.runtime/active_compact_semantic_memory_v1',[string]$VectorMapPath='operations/school/curriculum/development_vector/school_development_vector_map_v1.json')
$ErrorActionPreference='Stop'; $repoRoot=(git rev-parse --show-toplevel).Trim(); Set-Location $repoRoot
function Sha($p){if(Test-Path $p){(Get-FileHash $p -Algorithm SHA256).Hash}else{'MISSING'}}
function RunSel($root,$out,$topics='AUTO'){ & powershell -NoProfile -ExecutionPolicy Bypass -File operations/school/memory/select_dynamic_theme_cell_v1.ps1 -MemoryRoot $root -VectorMapPath $VectorMapPath -RequestedTopics $topics -OutputPath $out | Out-Null; if($LASTEXITCODE -ne 0){throw 'SELECTOR_NONZERO'}; Get-Content $out -Raw|ConvertFrom-Json }
$cells=Join-Path $MemoryRoot 'cells.jsonl'; $index=Join-Path $MemoryRoot 'index.json'; $manifest=Join-Path $MemoryRoot 'manifest.json'; $before=@{cells=Sha $cells;index=Sha $index;manifest=Sha $manifest}
$lab='.runtime/school_dynamic_theme_selection/contrast_validator'; if(Test-Path $lab){Remove-Item $lab -Recurse -Force}; New-Item -ItemType Directory -Force $lab|Out-Null
try{
  $a=Join-Path $lab 'a'; $b=Join-Path $lab 'b'; New-Item -ItemType Directory -Force $a,$b|Out-Null
  '{"status":"PASS_LAB"}'|Set-Content (Join-Path $a 'manifest.json') -Encoding UTF8; '{"status":"PASS_LAB"}'|Set-Content (Join-Path $b 'manifest.json') -Encoding UTF8
  '{"concept_key":"school_development_vector","label":"school development vector","observation_count":999,"summary":"proof validator source return_to_parent"}'|Set-Content (Join-Path $a 'cells.jsonl') -Encoding UTF8
  '{"concept_key":"development_lawfulness","label":"lawful development sequence","observation_count":1,"summary":"tiny"}'|Set-Content (Join-Path $b 'cells.jsonl') -Encoding UTF8
  $ra=RunSel $a (Join-Path $lab 'a.json'); $rb=RunSel $b (Join-Path $lab 'b.json'); $explicit=RunSel $a (Join-Path $lab 'explicit.json') 'development_lawfulness'
  $fail=@(); if($ra.status -ne 'PASS_DEVELOPMENT_VECTOR_THEME_SELECTION_V2' -or $rb.status -ne 'PASS_DEVELOPMENT_VECTOR_THEME_SELECTION_V2'){$fail+='BAD_STATUS'}; if($ra.memory_used_for_topic_selection -ne $false -or $rb.memory_used_for_topic_selection -ne $false){$fail+='MEMORY_USED_FOR_SELECTION'}; if($ra.selected_topic.topic_key -ne $rb.selected_topic.topic_key){$fail+='AUTO_TOPIC_CHANGED_WITH_MEMORY'}; if($explicit.selected_topic.topic_key -ne 'development_lawfulness'){$fail+='EXPLICIT_TOPIC_OVERRIDE_FAILED'}; if($ra.selection_boundary -ne 'TOPIC_SELECTED_BEFORE_MEMORY_RETRIEVAL'){$fail+='BOUNDARY_MISSING'}
  $after=@{cells=Sha $cells;index=Sha $index;manifest=Sha $manifest}; if($before.cells-ne$after.cells -or $before.index-ne$after.index -or $before.manifest-ne$after.manifest){$fail+='ACTIVE_MEMORY_CHANGED'}
  $status=if($fail.Count-eq 0){'PASS_MEMORY_INDEPENDENT_THEME_SELECTOR_V2'}else{'FAIL_MEMORY_INDEPENDENT_THEME_SELECTOR_V2'}; Write-Host "DEVELOPMENT_VECTOR_SELECTOR_VALIDATION_STATUS=$status"; Write-Host "AUTO_TOPIC_A=$($ra.selected_topic.topic_key)"; Write-Host "AUTO_TOPIC_B=$($rb.selected_topic.topic_key)"; Write-Host "EXPLICIT_TOPIC=$($explicit.selected_topic.topic_key)"; Write-Host "ACTIVE_MEMORY_CHANGED=$($before.cells-ne$after.cells)"; if($fail.Count){Write-Host ('FAILURES='+($fail-join ','));exit 1}
} finally { if(Test-Path $lab){Remove-Item $lab -Recurse -Force} }