param()
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Push-Location $repo
$targets=@('operations/autonomous_inner_motor/run_autonomous_inner_motor.ps1','operations/autonomous_inner_motor/start_agent_life_v1.ps1','operations/reasoning/build_agent_mind_logic_frame_v1.ps1','validators/validate_agent_life_multitick_productive_v1.ps1')
$errors=New-Object 'System.Collections.Generic.List[string]'
function Err([string]$m){[void]$errors.Add($m)}
$beforeTracked=@(git status --porcelain --untracked-files=no)
try {
 foreach($f in $targets){$tok=$null;$pe=$null;[System.Management.Automation.Language.Parser]::ParseFile((Resolve-Path $f),[ref]$tok,[ref]$pe)|Out-Null;if($pe.Count){Err ('parse:'+ $f+':'+(($pe|ForEach-Object Message)-join'|'))}}
 $runner=Get-Content 'operations/autonomous_inner_motor/run_autonomous_inner_motor.ps1' -Raw;$life=Get-Content 'operations/autonomous_inner_motor/start_agent_life_v1.ps1' -Raw;$mind=Get-Content 'operations/reasoning/build_agent_mind_logic_frame_v1.ps1' -Raw
 foreach($needle in @("[ValidateSet('Full','LifeLight')][string]`$LifeProfile='Full'","body_inspection_invoked=`$false","full_audit_deferred=`$true","'-ReasoningProfile','LifeCycle'","memory_is_command=`$false","memory_can_force_next_step=`$false")){if(-not$runner.Contains($needle)){Err ('runner_contract_missing:'+ $needle)}}
 if(-not$life.Contains("'-MemoryIngestionMode','Auto'")){Err 'life_not_auto_memory'};if($life -notmatch 'TickBudgetSeconds=35'){Err 'tick_budget_default_missing'}
 if($life -match '\$latest\s*=.*Get-ChildItem.*Sort-Object LastWriteTime.*Select-Object -First 1'){Err 'stale_latest_inheritance_pattern_present'}
 foreach($needle in @('BOUND_CURRENT_TICK_RUN_DIR','SANITATION_REFUSED_NOT_CURRENT_LIFE_OWNED','continuity_files_per_run_max=6','owned_continuity_dirs_max=$maxOwnedContinuityDirs')){if(-not$life.Contains($needle)){Err ('life_contract_missing:'+ $needle)}}
 foreach($needle in @("[ValidateSet('Full','LifeCycle')][string]`$ReasoningProfile='Full'","System.Collections.Generic.List[object]","`$known.ToArray()","DEFERRED_LIFE_CYCLE_PROFILE","memory_is_command=`$false")){if(-not$mind.Contains($needle)){Err ('mind_contract_missing:'+ $needle)}}
 if(-not$runner.Contains('New-LifeCycleLearningAtom') -or -not$runner.Contains('LIFE_LIGHT_WAITING_FOR_MIND_LOGIC') -or -not$runner.Contains('PASS_LIFE_LIGHT_THOUGHT_WITH_GOVERNED_MEMORY')){Err 'life_light_actual_reasoning_delta_contract_missing'}
if(-not$runner.Contains('PASS_LIFE_LIGHT_SHORT_TERM_STATE') -or -not$runner.Contains("buildTaskBoundedExecutor=[ordered]@{status='DEFERRED_LIFE_CYCLE_PROFILE'") -or -not$runner.Contains('$proofPackRequiredFiles=if($LifeProfile -eq ''LifeLight'')')){Err 'life_light_fast_finish_contract_missing'}
$known=New-Object 'System.Collections.Generic.List[object]';[void]$known.Add([ordered]@{claim='topic';evidence='input'});[void]$known.Add([ordered]@{claim='memory';evidence='memory'});if($known.Count-ne2 -or @($known.ToArray()).Count-ne2){Err 'known_collection_type_stability_failed'}
 $tok=$null;$pe=$null;$ast=[System.Management.Automation.Language.Parser]::ParseFile((Resolve-Path 'operations/autonomous_inner_motor/start_agent_life_v1.ps1'),[ref]$tok,[ref]$pe);$fn=@($ast.FindAll({param($n)$n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Invoke-AgentLifeOwnedRunSanitation'},$true))|Select-Object -First 1
 if(-not$fn){Err 'sanitation_function_ast_missing'} else { . ([scriptblock]::Create($fn.Extent.Text));$scratch=Join-Path '.runtime/self_development' ('agent_life_sanitation_validator_'+[guid]::NewGuid().ToString('N'));$aimo=Join-Path $scratch 'autonomous_inner_motor';$owned=Join-Path $aimo 'aimo_owned';$foreign=Join-Path $aimo 'aimo_foreign';New-Item -ItemType Directory -Force -Path $owned,$foreign|Out-Null;try{1..12|%{Set-Content -LiteralPath (Join-Path $owned ("file$_.json")) -Value '{}' -Encoding UTF8};foreach($n in @('memory_to_next_path_reuse_gate.json','short_term_mind_state.json','short_term_state_to_next_task_router.json','refocus_seed_diversification.json','refocus_to_new_thought_seed.json','action_decision_packet.json')){Set-Content -LiteralPath (Join-Path $owned $n) -Value '{}' -Encoding UTF8};$r=Invoke-AgentLifeOwnedRunSanitation -RunDir $owned -AimoRoot $aimo -OwnedRunDirs @($owned);if($r.status-ne'COMPACTED_SELF_OWNED_RUN_TO_CONTINUITY' -or (Get-ChildItem $owned -File).Count-gt6){Err 'owned_sanitation_compaction_failed'};$refused=$false;try{Invoke-AgentLifeOwnedRunSanitation -RunDir $foreign -AimoRoot $aimo -OwnedRunDirs @($owned)|Out-Null}catch{$refused=($_.Exception.Message -like 'SANITATION_REFUSED_NOT_CURRENT_LIFE_OWNED*')};if(-not$refused){Err 'foreign_sanitation_not_refused'}}finally{if(Test-Path $scratch){Remove-Item $scratch -Recurse -Force -ErrorAction SilentlyContinue}};if(Test-Path $scratch){Err 'validator_scratch_leftover'} }
 $afterTracked=@(git status --porcelain --untracked-files=no);if(($beforeTracked-join"`n")-ne($afterTracked-join"`n")){Err 'validator_mutated_tracked_repo_state'}
} finally {Pop-Location}
if($errors.Count){Write-Output ('FAIL_AGENT_LIFE_MULTITICK_PRODUCTIVE_V1|'+($errors-join';'));exit 1}
Write-Output 'PASS_AGENT_LIFE_MULTITICK_PRODUCTIVE_V1|STRUCTURE=PASS|MEMORY_NOT_COMMAND=PASS|TYPE_STABILITY=PASS|OWNED_SANITATION=PASS|FOREIGN_REFUSAL=PASS|SCRATCH_CLEAN=PASS|LIVE_MULTITICK=NOT_PROVEN_BY_THIS_VALIDATOR'
