$ErrorActionPreference='Stop'
$repoRoot=(git rev-parse --show-toplevel).Trim(); Set-Location $repoRoot
function Assert($Cond,[string]$Msg){if(-not $Cond){throw $Msg}}
function Write-Json([string]$Path,$Obj,[int]$Depth=100){$dir=Split-Path -Parent $Path;if($dir){New-Item -ItemType Directory -Force -Path $dir|Out-Null};$Obj|ConvertTo-Json -Depth $Depth|Set-Content $Path -Encoding UTF8}
$indexPath='self_model/organ_passports/_index/ORGAN_PASSPORT_DRAFT_INDEX_V1.json'
$signalsPath='reports/self_development/LIVING_LOOP_CURRENT_STATE_REFRESH_V1_SIGNALS.json'
$statePath='reports/self_development/LIVING_LOOP_CURRENT_STATE_REFRESH_V1_BODY_STATE.json'
$reasonPath='reports/self_development/LIVING_LOOP_CURRENT_STATE_REFRESH_V1_REASONER.json'
$decisionPath='reports/self_development/LIVING_LOOP_CURRENT_STATE_REFRESH_V1_DECISION.json'
$reportPath='reports/self_development/LIVING_LOOP_CURRENT_STATE_REFRESH_V1_REPORT.json'
$proofPath='tests/self_development/LIVING_LOOP_CURRENT_STATE_REFRESH_V1_PROOF.json'
Assert (Test-Path $indexPath) 'PASSPORT_INDEX_MISSING'
$idx=Get-Content $indexPath -Raw|ConvertFrom-Json
$organIds=@('operations_organ_promotion_lanes','operations_parallel_life','operations_live_like','operations_active_behavior')
$signals=@()
foreach($id in $organIds){
  $e=@($idx.entries|Where-Object{$_.organ_id -eq $id})|Select-Object -First 1
  Assert ($null -ne $e) "INDEX_ENTRY_MISSING:$id"
  Assert ($e.maturity -eq 'VALIDATED_LAB') "NOT_VALIDATED_LAB:$id"
  Assert ($e.live_or_lab_status -eq 'PROVEN_LAB') "NOT_PROVEN_LAB:$id"
  $signals += [ordered]@{signal_id=($id+'__VALIDATED_LAB_NON_ACTIVE_SIGNAL').ToUpperInvariant();organ_id=$id;signal_type='VALIDATED_LAB_NON_ACTIVE_SIGNAL';severity='info';confidence=1.0;lifecycle_decision='PROMOTE_TO_VALIDATED_LAB_KEEP_NON_ACTIVE';body_state='VALIDATED_LAB_NON_ACTIVE';evidence_ref=$e.passport_path;passport_ref=$e.passport_path;passport_index_ref=$indexPath;passport_active_created=$false;live_runtime_touched=$false;runtime_ready=$false;live_ready_claim=$false;autonomous_runtime=$false;recommended_outcome='ALLOW_AS_LAB_SIGNAL_NO_ACTIVE_AUTHORITY';brain_input_allowed=$true;reason='Current passport index shows validated lab/proven lab; no active/live authority granted.'}
  if($id -in @('operations_parallel_life','operations_live_like')){
    $signals += [ordered]@{signal_id=($id+'__BOUNDARY_GUARD_SIGNAL').ToUpperInvariant();organ_id=$id;signal_type='BOUNDARY_GUARD_SIGNAL';severity='high';confidence=1.0;lifecycle_decision='PROMOTE_TO_VALIDATED_LAB_KEEP_NON_ACTIVE';body_state='BOUNDARY_GUARDED_LAB_ONLY';evidence_ref=$e.passport_path;passport_ref=$e.passport_path;passport_index_ref=$indexPath;passport_active_created=$false;live_runtime_touched=$false;runtime_ready=$false;live_ready_claim=$false;autonomous_runtime=$false;recommended_outcome='PRESERVE_LAB_ONLY_BOUNDARY';brain_input_allowed=$true;reason='Boundary-sensitive lab signal; not live readiness or runtime authority.'}
  }
}
$signals += [ordered]@{signal_id='LIVING_LOOP_CURRENT_STATE_REFRESH__RETURN_TO_PARENT_SIGNAL';organ_id='living_loop_current_state_refresh_v1';signal_type='RETURN_TO_PARENT_SIGNAL';severity='info';confidence=1.0;lifecycle_decision='CONTINUE_PARENT_TASK';body_state='CURRENT_STATE_REFRESHED_AFTER_ACTIVE_BEHAVIOR_VALIDATION';evidence_ref=$indexPath;passport_ref='NOT_A_PASSPORTED_ORGAN_YET';passport_index_ref=$indexPath;passport_active_created=$false;live_runtime_touched=$false;runtime_ready=$false;live_ready_claim=$false;autonomous_runtime=$false;recommended_outcome='CONTINUE_NON_EXECUTING_LAYER_OR_PREPARE_NEXT_AUTHORITY_GATE';brain_input_allowed=$true;reason='Current chain refreshed after active behavior fresh 1000 lifecycle pass.'}
$validated=@($signals|Where-Object{$_.signal_type -eq 'VALIDATED_LAB_NON_ACTIVE_SIGNAL'})
$blocked=@($signals|Where-Object{$_.signal_type -like 'BLOCKED*'})
$boundary=@($signals|Where-Object{$_.signal_type -eq 'BOUNDARY_GUARD_SIGNAL'})
$return=@($signals|Where-Object{$_.signal_type -eq 'RETURN_TO_PARENT_SIGNAL'})
$body=[ordered]@{schema='living_loop_current_state_refresh_v1_body_state';status='PASS_LIVING_LOOP_CURRENT_STATE_REFRESH_V1_BODY_STATE';source='passport_index_current_after_active_behavior_fresh_1000';signals_ref=$signalsPath;categories=[ordered]@{validated_lab_non_active=$validated;blocked=@();boundary_guarded=$boundary;return_to_parent=$return;repair_required=@();owner_decision_required=@();no_action_needed=$validated};summary=[ordered]@{total_signals=@($signals).Count;validated_lab_non_active_count=@($validated).Count;blocked_count=0;boundary_guarded_count=@($boundary).Count;return_to_parent_count=@($return).Count;repair_required_count=0;owner_decision_required_count=0;no_action_needed_count=@($validated).Count;highest_severity='high';recommended_next_route='NO_BLOCKING_ROOT_CAUSE_CONTINUE_NON_EXECUTING_BRAIN_BUILD';brain_input_ready=$true;mutation_authorized=$false;runtime_ready=$false;live_ready=$false;autonomous_runtime=$false};created_at=(Get-Date).ToString('o')}
$findings=@()
foreach($v in $validated){$findings += [ordered]@{finding_id='VALIDATED_LAB_NON_ACTIVE_CAUSE__'+$v.organ_id;finding_class='VALIDATED_LAB_NON_ACTIVE_CAUSE';source_bucket='validated_lab_non_active';organ_id=$v.organ_id;symptom='Organ has current validated lab signal.';root_cause='Fresh/current passport evidence verifies lab state without active/live authority.';confidence=1.0;evidence_refs=@($v.evidence_ref);legal_action_class='ALLOW_AS_LAB_SIGNAL_NO_ACTIVE_AUTHORITY';forbidden_actions=@('CREATE_PASSPORT_ACTIVE','CLAIM_PROVEN_LIVE','CLAIM_RUNTIME_READY','MUTATE_WITHOUT_AUTHORITY');recommended_next_question_or_action_class='Continue non-executing Brain build or require separate authority for activation.';mutation_authorized=$false;runtime_ready=$false;live_ready=$false;autonomous_runtime=$false;brain_decision=$false;execution_performed=$false}}
foreach($b in $boundary){$findings += [ordered]@{finding_id='BOUNDARY_GUARD_ROOT_CAUSE__'+$b.organ_id;finding_class='BOUNDARY_GUARD_ROOT_CAUSE';source_bucket='boundary_guarded';organ_id=$b.organ_id;symptom='Signal is boundary-sensitive.';root_cause='Lab/observation evidence exists but does not grant live/runtime/autonomous authority.';confidence=1.0;evidence_refs=@($b.evidence_ref);legal_action_class='PRESERVE_BOUNDARY_OR_REQUEST_SEPARATE_LIVE_GATE';forbidden_actions=@('CLAIM_LIVE_READY','CLAIM_RUNTIME_READY','START_AUTONOMOUS_RUNTIME','CREATE_PASSPORT_ACTIVE');recommended_next_question_or_action_class='Preserve lab boundary; separate live gate required for live claims.';mutation_authorized=$false;runtime_ready=$false;live_ready=$false;autonomous_runtime=$false;brain_decision=$false;execution_performed=$false}}
$findings += [ordered]@{finding_id='RETURN_TO_PARENT_CAUSE__living_loop_current_state_refresh_v1';finding_class='RETURN_TO_PARENT_CAUSE';source_bucket='return_to_parent';organ_id='living_loop_current_state_refresh_v1';symptom='Old chain had stale blocked state.';root_cause='Active behavior fresh 1000 lifecycle pass changed body state; current chain needed refresh.';confidence=1.0;evidence_refs=@($indexPath);legal_action_class='RETURN_CURRENT_STATE_TO_PARENT';forbidden_actions=@('USE_STALE_BLOCKED_ROUTE','EXECUTE_WITHOUT_AUTHORITY');recommended_next_question_or_action_class='Return updated current state; continue non-executing Brain build.';mutation_authorized=$false;runtime_ready=$false;live_ready=$false;autonomous_runtime=$false;brain_decision=$false;execution_performed=$false}
$reason=[ordered]@{schema='living_loop_current_state_refresh_v1_reasoner';status='PASS_LIVING_LOOP_CURRENT_STATE_REFRESH_V1_REASONER';body_state_ref=$statePath;findings=$findings;summary=[ordered]@{finding_count=@($findings).Count;dominant_root_cause='NO_BLOCKING_ROOT_CAUSE';blocked_root_cause_present=$false;recommended_next_action_class='CONTINUE_NON_EXECUTING_BRAIN_BUILD_OR_SEPARATE_AUTHORITY_GATE';brain_input_ready=$true;mutation_authorized=$false;runtime_ready=$false;live_ready=$false;autonomous_runtime=$false;brain_decision=$false;execution_performed=$false};created_at=(Get-Date).ToString('o')}
$decision=[ordered]@{schema='living_loop_current_state_refresh_v1_decision';status='PASS_LIVING_LOOP_CURRENT_STATE_REFRESH_V1_DECISION';route_class='CONTINUE_NON_EXECUTING_BRAIN_BUILD_OR_SEPARATE_AUTHORITY_GATE';dominant_root_cause='NO_BLOCKING_ROOT_CAUSE';execution_allowed=$false;mutation_authorized=$false;runtime_ready=$false;live_ready=$false;autonomous_runtime=$false;brain_decision=$false;owner_decision_required=$false;evidence_refs=@($indexPath,$statePath,$reasonPath);forbidden_actions=@('USE_STALE_BLOCKED_ROUTE','CLAIM_LIVE_READY','MUTATE_WITHOUT_AUTHORITY','CREATE_PASSPORT_ACTIVE');return_to_parent_summary=[ordered]@{result='Current state refresh removed stale active_behavior blocked route.';next_safe_step='Continue non-executing Brain build or create separate authority gate for activation/live only by Owner decision.'};created_at=(Get-Date).ToString('o')}
$signalsDoc=[ordered]@{schema='living_loop_current_state_refresh_v1_signals';status='PASS_LIVING_LOOP_CURRENT_STATE_REFRESH_V1_SIGNALS';signals=$signals;created_at=(Get-Date).ToString('o')}
$report=[ordered]@{schema='living_loop_current_state_refresh_v1_report';status='PASS_LIVING_LOOP_CURRENT_STATE_REFRESH_V1';signals_ref=$signalsPath;body_state_ref=$statePath;reasoner_ref=$reasonPath;decision_ref=$decisionPath;summary=[ordered]@{validated_lab_non_active=4;blocked=0;repair_required=0;boundary_guarded=2;stale_blocked_route_removed=$true};boundary=[ordered]@{execution_allowed=$false;mutation_authorized=$false;runtime_ready=$false;live_ready=$false;autonomous_runtime=$false;no_passport_active_created=$true;no_live_runtime_touched=$true};created_at=(Get-Date).ToString('o')}
$proof=[ordered]@{schema='living_loop_current_state_refresh_v1_proof';status='PASS_LIVING_LOOP_CURRENT_STATE_REFRESH_V1';active_behavior_current_validated_lab=$true;validated_lab_non_active_count=4;blocked_count=0;repair_required_count=0;boundary_guard_count=2;stale_blocked_route_removed=$true;dominant_root_cause='NO_BLOCKING_ROOT_CAUSE';recommended_next_route='CONTINUE_NON_EXECUTING_BRAIN_BUILD_OR_SEPARATE_AUTHORITY_GATE';execution_allowed=$false;mutation_authorized=$false;runtime_ready=$false;live_ready=$false;autonomous_runtime=$false;no_passport_active_created=$true;no_live_runtime_touched=$true;report_path=$reportPath;created_at=(Get-Date).ToString('o')}
Write-Json $signalsPath $signalsDoc 100
Write-Json $statePath $body 100
Write-Json $reasonPath $reason 100
Write-Json $decisionPath $decision 100
Write-Json $reportPath $report 100
Write-Json $proofPath $proof 100
Write-Host 'BUILD_PASS=PASS_LIVING_LOOP_CURRENT_STATE_REFRESH_V1'
Write-Host 'VALIDATED_LAB_NON_ACTIVE=4'
Write-Host 'BLOCKED=0'
Write-Host 'REPAIR_REQUIRED=0'
Write-Host 'DOMINANT_ROOT_CAUSE=NO_BLOCKING_ROOT_CAUSE'
