$ErrorActionPreference='Stop'
$repoRoot=(git rev-parse --show-toplevel).Trim(); Set-Location $repoRoot
function Assert($Cond,[string]$Msg){ if(-not $Cond){ throw $Msg } }
$req='contracts/living_loop/BRAIN_SELECTOR_STUB_V1_REQUIREMENT.md'
$intentPath='reports/self_development/BRAIN_SELECTOR_STUB_V1_INTENT.json'
$reportPath='reports/self_development/BRAIN_SELECTOR_STUB_V1_REPORT.json'
$proofPath='tests/self_development/BRAIN_SELECTOR_STUB_V1_PROOF.json'
foreach($p in @($req,$intentPath,$reportPath,$proofPath)){Assert (Test-Path $p) "MISSING:$p"}
powershell -ExecutionPolicy Bypass -File operations/living_loop/validate_brain_input_consumer_v1.ps1 | Out-Host
Assert ($LASTEXITCODE -eq 0) 'BRAIN_INPUT_CONSUMER_VALIDATION_FAILED'
$i=Get-Content $intentPath -Raw|ConvertFrom-Json
$r=Get-Content $reportPath -Raw|ConvertFrom-Json
$p=Get-Content $proofPath -Raw|ConvertFrom-Json
Assert ($i.status -eq 'PASS_BRAIN_SELECTOR_STUB_V1_INTENT') 'INTENT_STATUS_BAD'
Assert ($r.status -eq 'PASS_BRAIN_SELECTOR_STUB_V1') 'REPORT_STATUS_BAD'
Assert ($p.status -eq 'PASS_BRAIN_SELECTOR_STUB_V1') 'PROOF_STATUS_BAD'
Assert ($i.intent_class -eq 'REQUEST_OWNER_AUTHORIZED_PREFLIGHT_REPAIR_OR_KEEP_BLOCKED') 'INTENT_CLASS_BAD'
Assert ($i.target_organ_id -eq 'operations_active_behavior') 'TARGET_BAD'
Assert ($i.source_route_class -eq 'REPAIR_SOURCE_PROOF_OR_KEEP_BLOCKED') 'SOURCE_ROUTE_BAD'
Assert ($i.owner_decision_required -eq $true) 'OWNER_DECISION_DROPPED'
Assert ($i.selected_by_brain_stub -eq $true) 'NOT_SELECTED_BY_STUB'
Assert ($i.full_brain -eq $false) 'FULL_BRAIN_OVERCLAIM'
Assert ($i.execution_allowed -eq $false) 'EXECUTION_OVERCLAIM'
Assert ($i.mutation_authorized -eq $false) 'MUTATION_OVERCLAIM'
Assert ($i.brain_can_execute -eq $false) 'BRAIN_EXECUTE_OVERCLAIM'
Assert ($i.brain_can_mutate -eq $false) 'BRAIN_MUTATE_OVERCLAIM'
Assert ($i.runtime_ready -eq $false) 'RUNTIME_READY_OVERCLAIM'
Assert ($i.live_ready -eq $false) 'LIVE_READY_OVERCLAIM'
Assert ($i.autonomous_runtime -eq $false) 'AUTONOMOUS_OVERCLAIM'
Assert ($i.passport_active_allowed -eq $false) 'PASSPORT_ACTIVE_OVERCLAIM'
Assert ($i.requires_preflight -eq $true) 'PREFLIGHT_NOT_REQUIRED'
Assert ($i.requires_owner_authority -eq $true) 'OWNER_AUTHORITY_NOT_REQUIRED'
Assert (@($i.evidence_refs).Count -gt 0) 'EVIDENCE_REFS_MISSING'
Assert (@($i.forbidden_actions).Count -gt 0) 'FORBIDDEN_ACTIONS_MISSING'
Assert (@($i.stop_conditions).Count -ge 3) 'STOP_CONDITIONS_MISSING'
Assert ($p.selected_intent_matches_route -eq $true) 'INTENT_ROUTE_MATCH_BAD'
Assert ($p.target_preserved -eq $true) 'TARGET_NOT_PRESERVED'
Assert ($p.owner_decision_required_preserved -eq $true) 'OWNER_DECISION_NOT_PRESERVED'
Assert ($p.execution_allowed -eq $false) 'PROOF_EXECUTION_OVERCLAIM'
Assert ($p.mutation_authorized -eq $false) 'PROOF_MUTATION_OVERCLAIM'
Assert ($p.full_brain -eq $false) 'PROOF_FULL_BRAIN_OVERCLAIM'
Write-Host 'VALIDATION_PASS=PASS_BRAIN_SELECTOR_STUB_V1'
Write-Host 'INTENT_CLASS=REQUEST_OWNER_AUTHORIZED_PREFLIGHT_REPAIR_OR_KEEP_BLOCKED'
Write-Host 'TARGET=operations_active_behavior'
Write-Host 'FULL_BRAIN=false'
Write-Host 'EXECUTION_ALLOWED=false'
Write-Host 'MUTATION_AUTHORIZED=false'
