$ErrorActionPreference='Stop'
$repoRoot=(git rev-parse --show-toplevel).Trim(); Set-Location $repoRoot
function Assert($Cond,[string]$Msg){ if(-not $Cond){ throw $Msg } }
$req='contracts/living_loop/BRAIN_INPUT_CONSUMER_V1_REQUIREMENT.md'
$envelopePath='reports/self_development/BRAIN_INPUT_CONSUMER_V1_ENVELOPE.json'
$reportPath='reports/self_development/BRAIN_INPUT_CONSUMER_V1_REPORT.json'
$proofPath='tests/self_development/BRAIN_INPUT_CONSUMER_V1_PROOF.json'
foreach($p in @($req,$envelopePath,$reportPath,$proofPath)){Assert (Test-Path $p) "MISSING:$p"}
powershell -ExecutionPolicy Bypass -File operations/living_loop/validate_decision_gate_v1.ps1 | Out-Host
Assert ($LASTEXITCODE -eq 0) 'DECISION_GATE_VALIDATION_FAILED'
$e=Get-Content $envelopePath -Raw|ConvertFrom-Json
$r=Get-Content $reportPath -Raw|ConvertFrom-Json
$p=Get-Content $proofPath -Raw|ConvertFrom-Json
Assert ($e.status -eq 'PASS_BRAIN_INPUT_CONSUMER_V1_ENVELOPE') 'ENVELOPE_STATUS_BAD'
Assert ($r.status -eq 'PASS_BRAIN_INPUT_CONSUMER_V1') 'REPORT_STATUS_BAD'
Assert ($p.status -eq 'PASS_BRAIN_INPUT_CONSUMER_V1') 'PROOF_STATUS_BAD'
Assert ($e.input_class -eq 'OWNER_DECISION_REQUIRED_REPAIR_OR_KEEP_BLOCKED') 'INPUT_CLASS_BAD'
Assert ($e.route_class -eq 'REPAIR_SOURCE_PROOF_OR_KEEP_BLOCKED') 'ROUTE_CLASS_BAD'
Assert ($e.target_organ_id -eq 'operations_active_behavior') 'TARGET_BAD'
Assert ($e.owner_decision_required -eq $true) 'OWNER_DECISION_REQUIRED_DROPPED'
Assert ($e.brain_can_read -eq $true) 'BRAIN_CAN_READ_BAD'
Assert ($e.brain_can_execute -eq $false) 'BRAIN_CAN_EXECUTE_OVERCLAIM'
Assert ($e.brain_can_mutate -eq $false) 'BRAIN_CAN_MUTATE_OVERCLAIM'
Assert ($e.execution_allowed -eq $false) 'EXECUTION_ALLOWED_OVERCLAIM'
Assert ($e.mutation_authorized -eq $false) 'MUTATION_AUTHORIZED_OVERCLAIM'
Assert ($e.brain_decision -eq $false) 'BRAIN_DECISION_OVERCLAIM'
Assert ($e.passport_active_allowed -eq $false) 'PASSPORT_ACTIVE_OVERCLAIM'
Assert ($e.runtime_ready -eq $false) 'RUNTIME_READY_OVERCLAIM'
Assert ($e.live_ready -eq $false) 'LIVE_READY_OVERCLAIM'
Assert ($e.autonomous_runtime -eq $false) 'AUTONOMOUS_OVERCLAIM'
Assert (@($e.evidence_refs).Count -gt 0) 'EVIDENCE_REFS_MISSING'
Assert (@($e.forbidden_actions).Count -gt 0) 'FORBIDDEN_ACTIONS_MISSING'
Assert (-not [string]::IsNullOrWhiteSpace($e.required_owner_question)) 'OWNER_QUESTION_MISSING'
Assert ($e.return_to_parent_summary.PSObject.Properties.Name -contains 'result') 'RETURN_SUMMARY_MISSING'
Assert ($p.route_class_preserved -eq $true) 'ROUTE_NOT_PRESERVED'
Assert ($p.target_preserved -eq $true) 'TARGET_NOT_PRESERVED'
Assert ($p.owner_decision_required_preserved -eq $true) 'OWNER_DECISION_NOT_PRESERVED'
Assert ($p.evidence_refs_preserved -eq $true) 'EVIDENCE_NOT_PRESERVED'
Assert ($p.forbidden_actions_preserved -eq $true) 'FORBIDDEN_NOT_PRESERVED'
Assert ($p.required_owner_question_present -eq $true) 'OWNER_QUESTION_PROOF_BAD'
Assert ($p.brain_can_read -eq $true) 'PROOF_BRAIN_READ_BAD'
Assert ($p.brain_can_execute -eq $false) 'PROOF_BRAIN_EXECUTE_OVERCLAIM'
Assert ($p.brain_can_mutate -eq $false) 'PROOF_BRAIN_MUTATE_OVERCLAIM'
Write-Host 'VALIDATION_PASS=PASS_BRAIN_INPUT_CONSUMER_V1'
Write-Host 'INPUT_CLASS=OWNER_DECISION_REQUIRED_REPAIR_OR_KEEP_BLOCKED'
Write-Host 'ROUTE_CLASS=REPAIR_SOURCE_PROOF_OR_KEEP_BLOCKED'
Write-Host 'BRAIN_CAN_READ=true'
Write-Host 'BRAIN_CAN_EXECUTE=false'
Write-Host 'BRAIN_CAN_MUTATE=false'
Write-Host 'OWNER_DECISION_REQUIRED=true'
